name: double_back_to_close_app
description: A Flutter package that allows Android users to press the back-button twice to close the app.
version: 1.0.0
homepage: https://github.com/hugocbpassos/double_back_to_close_app
issue_tracker: https://github.com/hugocbpassos/double_back_to_close_app/issues

environment:
  sdk: ">=2.1.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.1
